### ISSUE TITLE
Bugged Skull block textures

### ISSUE THREAD

**Issue by MrFastZombie** [GillianGroks/MissingMobs-Skeletons#1]
Skull blocks appear to have their textures bugged with this resource pack.
![javaw_V19Hz60gOD](https://github.com/GillianGroks/MissingMobs-Skeletons/assets/18253497/6b0cbb08-acdc-4da9-8311-a02cc607a22d)
![javaw_vaiR4HBavR](https://github.com/GillianGroks/MissingMobs-Skeletons/assets/18253497/fcfb9863-cb1b-4b01-8385-cf83858f271a)

**Comment by GillianGroks** [comment]
Thanks for letting me know. I'll get working on that now.

**Comment by GillianGroks** [comment]
Skull models & textures have now been fixed, and will only display the vanilla textures.

Version 1.01 is now uploaded to Modrinth.
